const symbolGroups = [
['AEVOUSDT_PERP.A,METISUSDT_PERP.A,MANTAUSDT_PERP.A,RPLUSDT_PERP.A,ANIMEUSDT_PERP.A,ICXUSDT_PERP.A,FLUXUSDT_PERP.A,BOMEUSDT_PERP.A,PIXELUSDT_PERP.A,PROMUSDT_PERP.A,USUALUSDT_PERP.A,MEMEUSDT_PERP.A,WAXPUSDT_PERP.A,AIXBTUSDT_PERP.A,SPELLUSDT_PERP.A,LSKUSDT_PERP.A,XVSUSDT_PERP.A,BIGTIMEUSDT_PERP.A,API3USDT_PERP.A,RLCUSDT_PERP.A'] , 
['SONICUSDT_PERP.A,SSVUSDT_PERP.A,IOSTUSDT_PERP.A,POWRUSDT_PERP.A,PHAUSDT_PERP.A,PEOPLEUSDT_PERP.A,DYMUSDT_PERP.A,CHRUSDT_PERP.A,YGGUSDT_PERP.A,ONGUSDT_PERP.A,CETUSUSDT_PERP.A,XVGUSDT_PERP.A,DOGSUSDT_PERP.A,ILVUSDT_PERP.A,BANANAUSDT_PERP.A,PARTIUSDT_PERP.A,VVVUSDT_PERP.A,CELRUSDT_PERP.A,TRBUSDT_PERP.A,CGPTUSDT_PERP.A'],
['DENTUSDT_PERP.A,JOEUSDT_PERP.A,KMNOUSDT_PERP.A,AGLDUSDT_PERP.A,DFUSDT_PERP.A,ALCHUSDT_PERP.A,BBUSDT_PERP.A,XAIUSDT_PERP.A,LQTYUSDT_PERP.A,TNSRUSDT_PERP.A,SHELLUSDT_PERP.A,USTCUSDT_PERP.A,KNCUSDT_PERP.A,OXTUSDT_PERP.A,NMRUSDT_PERP.A,SCRUSDT_PERP.A,STEEMUSDT_PERP.A,C98USDT_PERP.A,SCRTUSDT_PERP.A,BANANAS31USDT_PERP.A'],
['VANRYUSDT_PERP.A,MTLUSDT_PERP.A,ARKUSDT_PERP.A,HIFIUSDT_PERP.A,CTSIUSDT_PERP.A,GOATUSDT_PERP.A,PONKEUSDT_PERP.A,EDUUSDT_PERP.A,MOVRUSDT_PERP.A,COOKIEUSDT_PERP.A,BELUSDT_PERP.A,TSTUSDT_PERP.A,CYBERUSDT_PERP.A,BANUSDT_PERP.A,RAREUSDT_PERP.A,LUMIAUSDT_PERP.A,GPSUSDT_PERP.A,DODOXUSDT_PERP.A,AIUSDT_PERP.A,DUSKUSDT_PERP.A'],
['OMNIUSDT_PERP.A,BNTUSDT_PERP.A,ALICEUSDT_PERP.A,ARCUSDT_PERP.A,SOLVUSDT_PERP.A,TRUUSDT_PERP.A,NTRNUSDT_PERP.A,PORTALUSDT_PERP.A,DIAUSDT_PERP.A,DEGENUSDT_PERP.A,HIGHUSDT_PERP.A,OGNUSDT_PERP.A,RIFUSDT_PERP.A,CATIUSDT_PERP.A,STGUSDT_PERP.A,GRIFFAINUSDT_PERP.A,SAGAUSDT_PERP.A,ARPAUSDT_PERP.A,BAKEUSDT_PERP.A,MOODENGUSDT_PERP.A'],

];





module.exports = symbolGroups;

