const symbolGroups = [
['PROMUSDT_PERP.A,HIGHUSDT_PERP.A,PHBUSDT_PERP.A,HOOKUSDT_PERP.A,XEMUSDT_PERP.A,IOSTUSDT_PERP.A,OMGUSDT_PERP.A,KDAUSDT_PERP.A,PEOPLEUSDT_PERP.A,GRTUSDT_PERP.A,OXTUSDT_PERP.A,ALGOUSDT_PERP.A,EOSUSDT_PERP.A,NEOUSDT_PERP.A,THETAUSDT_PERP.A,VETUSDT_PERP.A,XTZUSDT_PERP.A,BATUSDT_PERP.A,ENJUSDT_PERP.A,KNCUSDT_PERP.A'],
['IOUSDT_PERP.A,SAFEUSDT_PERP.A,DOGSUSDT_PERP.A,NEIROUSDT_PERP.A,HMSTRUSDT_PERP.A,CATIUSDT_PERP.A,EIGENUSDT_PERP.A,SCRUSDT_PERP.A,MOODENGUSDT_PERP.A,GOATUSDT_PERP.A,PNUTUSDT_PERP.A,ACTUSDT_PERP.A,GRASSUSDT_PERP.A,HIPPOUSDT_PERP.A,PUFFERUSDT_PERP.A,MEUSDT_PERP.A,SWELLUSDT_PERP.A,UXLINKUSDT_PERP.A,KAIAUSDT_PERP.A,TROYUSDT_PERP.A'],
['VANRYUSDT_PERP.A,POLYXUSDT_PERP.A,SYSUSDT_PERP.A,DATAUSDT_PERP.A,SUNUSDT_PERP.A,VOXELUSDT_PERP.A,DEGENUSDT_PERP.A,MAVUSDT_PERP.A,MYROUSDT_PERP.A,RAYSOLUSDT_PERP.A,SAGAUSDT_PERP.A,TAIKOUSDT_PERP.A,OMUSDT_PERP.A,METISUSDT_PERP.A,ZENUSDT_PERP.A,CVCUSDT_PERP.A,BATUSDT_PERP.A,LSKUSDT_PERP.A,STEEMUSDT_PERP.A,STRAXUSDT_PERP.A'],
['FIOUSDT_PERP.A,HNTUSDT_PERP.A,ARKMUSDT_PERP.A,MBLUSDT_PERP.A,BNTUSDT_PERP.A,CKBUSDT_PERP.A,TRUUSDT_PERP.A,TUSDT_PERP.A,POLUSDT_PERP.A,XNOUSDT_PERP.A,GASUSDT_PERP.A,WAXPUSDT_PERP.A,VELODROMEUSDT_PERP.A,RPLUSDT_PERP.A,PONDUSDT_PERP.A,OMGUSDT_PERP.A,NULSUSDT_PERP.A,MOVRUSDT_PERP.A,LOKAUSDT_PERP.A,LQTYUSDT_PERP.A'],
['KASUSDT_PERP.A,JASMYUSDT_PERP.A,IRISUSDT_PERP.A,IFUSDT_PERP.A,HOOKUSDT_PERP.A,FORTHUSDT_PERP.A,FIDAUSDT_PERP.A,FARMUSDT_PERP.A,ETHWUSDT_PERP.A,EPXUSDT_PERP.A,DIAUSDT_PERP.A,DEXEUSDT_PERP.A,DEFIUSDT_PERP.A,CVPUSDT_PERP.A,CREAMUSDT_PERP.A,COSUSDT_PERP.A,COMPUSDT_PERP.A,CLVUSDT_PERP.A,CFXUSDT_PERP.A,CEEKUSDT_PERP.A'],

];





module.exports = symbolGroups;

