const symbolGroups = [
['BRETTUSDT_PERP.A, POPCATUSDT_PERP.A, SUNUSDT_PERP.A, DOGSUSDT_PERP.A, MBOXUSDT_PERP.A, FLUXUSDT_PERP.A, RPLUSDT_PERP.A, POLUSDT_PERP.A, 1MBABYDOGEUSDT_PERP.A, NEIROUSDT_PERP.A, FIDAUSDT_PERP.A, CATIUSDT_PERP.A, HMSTRUSDT_PERP.A, EIGENUSDT_PERP.A, DIAUSDT_PERP.A, 1000CATUSDT_PERP.A, SCRUSDT_PERP.A, GOATUSDT_PERP.A, MOODENGUSDT_PERP.A, SAFEUSDT_PERP.A'],
['SANTOSUSDT_PERP.A, COWUSDT_PERP.A, CETUSUSDT_PERP.A, 1000000MOGUSDT_PERP.A, GRASSUSDT_PERP.A, DRIFTUSDT_PERP.A, ACTUSDT_PERP.A, PNUTUSDT_PERP.A, BANUSDT_PERP.A, AKTUSDT_PERP.A, SCRTUSDT_PERP.A, 1000CHEEMSUSDT_PERP.A, THEUSDT_PERP.A, MORPHOUSDT_PERP.A, CHILLGUYUSDT_PERP.A, KAIAUSDT_PERP.A, AEROUSDT_PERP.A, ACXUSDT_PERP.A, ORCAUSDT_PERP.A, MOVEUSDT_PERP.A'],
['RAYSOLUSDT_PERP.A, KOMAUSDT_PERP.A, VIRTUALUSDT_PERP.A, SPXUSDT_PERP.A, MEUSDT_PERP.A, AVAUSDT_PERP.A, VELODROMEUSDT_PERP.A, MOCAUSDT_PERP.A, VANAUSDT_PERP.A, PENGUUSDT_PERP.A, LUMIAUSDT_PERP.A, USUALUSDT_PERP.A, AIXBTUSDT_PERP.A, FARTCOINUSDT_PERP.A, KMNOUSDT_PERP.A, CGPTUSDT_PERP.A, HIVEUSDT_PERP.A, DEXEUSDT_PERP.A, PHAUSDT_PERP.A, GRIFFAINUSDT_PERP.A'],
['ZEREBROUSDT_PERP.A, BIOUSDT_PERP.A, COOKIEUSDT_PERP.A, ALCHUSDT_PERP.A, SWARMSUSDT_PERP.A, SONICUSDT_PERP.A, DUSDT_PERP.A, PROMUSDT_PERP.A, SUSDT_PERP.A, SOLVUSDT_PERP.A, ARCUSDT_PERP.A, AVAAIUSDT_PERP.A, TRUMPUSDT_PERP.A, MELANIAUSDT_PERP.A, VTHOUSDT_PERP.A, ANIMEUSDT_PERP.A, PIPPINUSDT_PERP.A, VVVUSDT_PERP.A, BERAUSDT_PERP.A, TSTUSDT_PERP.A'],
['LAYERUSDT_PERP.A, HEIUSDT_PERP.A, IPUSDT_PERP.A, GPSUSDT_PERP.A, SHELLUSDT_PERP.A, KAITOUSDT_PERP.A, REDUSDT_PERP.A, VICUSDT_PERP.A, EPICUSDT_PERP.A, BMTUSDT_PERP.A, MUBARAKUSDT_PERP.A, FORMUSDT_PERP.A, TUTUSDT_PERP.A, BROCCOLI714USDT_PERP.A, BROCCOLIF3BUSDT_PERP.A, SIRENUSDT_PERP.A, BANANAS31USDT_PERP.A, BRUSDT_PERP.A, PLUMEUSDT_PERP.A, NILUSDT_PERP.A'],

];





module.exports = symbolGroups;

